### PR TITLE
Change date diff algorithm and change problems with tests, also add some refactoring

### PR DESCRIPTION
**Pull request by HotTaton**
Hi! We are faced with bug, when months count was -1. You are can reproduce it, by using get diff method for 2018.11.28 and 2019.11.27. If you need more information, you can contact me: (skype: veefomit_llirik).
Also, I've changed some unit tests. They work wrong because of 2020 is leap year.

### CODE REVIEW

**Comment by HotTaton** [comment]
Hi again! I've rewrite GetDiff algorithm to fix several bugs with calculations.
Also I found, that operation GetDiff in some cases is non-сommutative. 
Sometimes in cases, when next year will be leap, we have that operation DateTime.Now - DateTime.Now.AddSeconds(6).AddMinutes(5).AddHours(4).AddDays(3).AddMonths(2).AddYears(2) will not be equal DateTime.AddSeconds(6).AddMinutes(5).AddHours(4).AddDays(3).AddMonths(2).AddYears(2) - DateTime.Now. In C# librarary NodaTime and Java's LocalDate "until" method I've also faced with similar problem. I think there is no algorithm, that can make this operation commutative (anyway I can't found "right one"). But maybe you can find solution better than my.
For now I've fix some tests to make this right and change DateTime.Now to constant DateTime value. I think we need more tests with const values in future.
Anyway, thx for great library, hope I've help you!

**Comment by joaomatossilva** [comment]
Hi, thanks.

Indeed never in anyway should a date diff output a -1 for any value, so thanks for spotting that out.

Regarding the implementation, I need to think a little bit more about it. on the case that wasn't working for you, I'm not entirely convinved it should say 11 months and 30 days. The output should be more Natural, and less Numeric. 30 days are a month, and 12 months are one year. Again.. I need to think a little bit more about it. I don't discard the possibility of having multiple strategies, but to me, this would be a 11month, 29 days.


Also, yes, it's not comutative, and not a few minutes ago, I was fixing something also related to that. And it's not trivial to guess the opposite operations because the number of days are not equal for every month.
I'll give you an example, on 10 Januray, if you add 10 days and 1 month (by this order) you get 28-fev on a non leap year or 29-fev on a leap year. IF you add it on reverse, you get 02-mar or 01-mar, again depending if it's leap or not. This is why the DateDiff should take the more natural or human expression of the difference, but again, I'm not yet 100% sure of it.

**Comment by joaomatossilva** [comment]
I've "fixed" the issue on a more naive way. It wont get the result that you want, but I do think it makes more sense the output.

**Comment by HotTaton** [comment]
Thanks!

**Pull request closed without merging**
