### PR TITLE
Added Polish Natural Time Strategy and Polish Holiday Strategy

### PR DESCRIPTION
**Pull request by scoutboy420**
Added Holidays in Poland and Polish Natural Time Strategy. Needed some modification of base methods, because in Polish declination depends on the last digit of a number so I had to pass the value to Pluralize method. I did that in a way to not screw up already made Natural Time Strategies and to make it easier for other languages that need exact value for declination. From my tests, it is working as intended. 

Though it may need some refactoring and possible optimizations.

### CODE REVIEW

**Comment by joaomatossilva** [comment]
Hi,

Thanks. I see what your problem was here. And maybe on other languages it will be the same.
What I don't like is to base classes have to inherit from a Pluralize or the other depending if they set a property.

I would change all the Pluralize to yours, and release this on the next major release (I also have some other breaking changes to relase soon), and drop that new Property since it won't be needed anymore.

What do you think? It's a bit of an effort to change all other implementations that do override the Pluralize, but I think it's a leaner approach.

**Comment by scoutboy420** [comment]
@joaomatossilva Yeah, if you are ok with that, it would be the best approach

**Comment by scoutboy420** [comment]
Should be good now

**Comment by joaomatossilva** [comment]
LGTM, thanks

**Comment by joaomatossilva** [comment]
as soon I'll finish the regional holidays I'll release this on a 5.0 version

**Pull request merged**
