### PR TITLE
EN_JM Adding Holidays for Jamaica

### PR DESCRIPTION
**Pull request by anselantz**
This also involved adding support for .netframework 4.6.1 since 4.5 is end of life.

### CODE REVIEW

**Comment by anselantz** [comment]
not sure how to approach this, any suggestions would be good. 
Problem: If a holiday falls on a Sunday, it is observed on the Monday. Also for back to back holidays e.g. Christmas and Boxing Day as is the case for 2022, if the if a holiday falls on a Sunday and is Observed on a Monday, the Holiday that would be on the Monday is now observed on Tuesday.

**Comment by anselantz** [comment]
build fails on .netstandard 1.5

**Comment by joaomatossilva** [comment]
I like the implementation. Can you clean the Implemation from the target frameworks? I think I'll clear up and remove all framework and old net standards.

I think I'll leave it up with just netstandard2.0

**Comment by anselantz** [comment]
I updated, I'll leave it to you from here

**Comment by joaomatossilva** [comment]
I still see changes on the csproj.

Can you rebase your changes?

**Comment by joaomatossilva** [comment]
Finally a green build.

Merging

**Comment by Jadabillingsisathief** [comment]
> This also involved adding support for .netframework 4.6.1 since 4.5 is end of life.

Help me Theronda powell 2/11/1979 4048397291 jada billings octobocat is stalking tracking money laundering fraud ppp you name it very inhumane stealung from my family and i ssdi benefits etc..... 10/9/2000 she is a regisyered small business owner in Atlanta working us fraduently pleasehelp!!!!!!!!!!! Inteenet is the Devil!!

**Pull request merged**
