### PR TITLE
Indian Holiday 

### PR DESCRIPTION
**Pull request by AnirudhG07**
@joaomatossilva This contains 2 files on Indian Holidays. It has both Strategies and Tests. This is based on Chinese Calendar files since Both follow the Lunisolar Calendar system.<br>
  It contains a few among many holidays, I have added the most prominent 6 of the festivals.

### CODE REVIEW

**Comment by joaomatossilva** [comment]
I was wondering why the Build was not working, but then I found that Indian Holidays were already implemented 7 years ago: https://github.com/joaomatossilva/DateTimeExtensions/blob/master/src/DateTimeExtensions/WorkingDays/CultureStrategies/IndianHolidayStrategy.cs

maybe you could update that strategy with yours, if it's more complete

**Comment by joaomatossilva** [comment]
you can visualize it here: https://datetimeextensions.azurewebsites.net/Calendar/en-IN/2024

**Comment by AnirudhG07** [comment]
> I was wondering why the Build was not working, but then I found that Indian Holidays were already implemented 7 years ago: https://github.com/joaomatossilva/DateTimeExtensions/blob/master/src/DateTimeExtensions/WorkingDays/CultureStrategies/IndianHolidayStrategy.cs
> 
> maybe you could update that strategy with yours, if it's more complete

I checked the code and i had updated more holidays than whats given. So I can update that and make a PR w.r.t that code.

**Comment by joaomatossilva** [comment]
Looking forward to it

**Review by gdamiaN538 — COMMENTED** [review]
src/DateTimeExtensions/IndianHolidays.md

**Review by Nagoy0616 — APPROVED** [review]

**Review by Nagoy0616 — APPROVED** [review]

**Comment by AnirudhG07** [comment]
Sorry I was out of touch. I will be making the following changes to get this PR complete.
1) deleting the files i put and replace with previously present ones in the same location IndianHoliday ones.
2) I will be changing the files and adding some more holidays. Indian Holidays has some government set National Holidays, fixed festive holidays and optional festive holidays. 

Net 3 files would be added as before.

**Comment by AnirudhG07** [comment]
Oh by the way, i noticed. the original indian holiday file has #region License
Is it possible to change it??? :{|

**Comment by joaomatossilva** [comment]
You can remove it

**Review by Sykeslaura799 — COMMENTED** [review]
IDK how all this developer stuff works I can only see it coming through can someone explain to me why is my name involved ?

**Comment by joaomatossilva** [comment]
@AnirudhG07 
Can you rebase and check the failing automatic tests?
Can't merge this if the build is not green

**Comment by Sykeslaura799** [comment]
Is it about my land or crypto ? I was reading on my phone how someone was trying to say the vendor had died and a bunch of other codes ?
>

**Pull request closed without merging**
